import openpyxl
from collections import OrderedDict

# Load existing workbook
wb = openpyxl.load_workbook('ai_ml_companies_list.xlsx')
ws = wb.active

# Read existing companies
existing = OrderedDict()
for row in ws.iter_rows(min_row=2, values_only=True):
    company, url = row[0], row[1]
    if company:
        existing[company.strip()] = url

print(f"Original count: {len(existing)}")

# Companies to REMOVE (from agent 1 analysis)
remove_list = [
    # Pure Drug Discovery / Biotech / Pharma
    "Insitro", "Formation Bio", "BigHat Biosciences", "EvolutionaryScale",
    "Generate:Biomedicines", "Exscientia", "Synthego", "Insilico Medicine",
    "Atomwise", "Recursion Pharmaceuticals", "Isomorphic Labs", "Cradle Bio",
    "Iktos", "Absci", "Benevolent AI", "Relay Therapeutics", "Deep Genomics",
    "Valo Health", "XtalPi",
    # Non-Tech Insurance
    "Cowbell Cyber", "Corgi Insurance", "Coterie Insurance", "Embroker",
    "Hippo Insurance", "Root Insurance",
    # Pure Robotics Hardware
    "Boston Dynamics", "Agility Robotics", "Standard Bots", "ABB Robotics",
    "FANUC", "KUKA Robotics", "Unitree Robotics", "Kawasaki Robotics",
    "Hanson Robotics", "Miso Robotics", "Universal Robots", "Doosan Robotics",
    "Comau", "Scythe Robotics", "Veo Robotics", "inVia Robotics",
    "Bedrock Robotics", "Richtech Robotics",
    # Agriculture / Farming Hardware
    "Monarch Tractor", "Carbon Robotics", "Bonsai Robotics", "Red Barn Robotics",
    "Solinftec", "iFarm", "Halter", "Sencrop", "Ecorobotix", "Farmblox",
    "Bindwell", "Aydi", "FarmWise",
    # Non-Tech Consulting
    "McKinsey & Company", "BCG (Boston Consulting Group)", "Six Paths Consulting",
    # Traditional Telecom / Hardware
    "Ericsson", "Nokia", "Huawei", "ZTE", "Vodafone", "Telefonica",
    # Defunct / Acquired
    "Pymetrics (Harver)", "Drift (Salesloft)", "Knewton (Wiley)",
    "GraphCore (now part of SoftBank)", "Blue Prism (SS&C)",
    "Chorus.ai (ZoomInfo)", "MLflow (Databricks)", "Sora (OpenAI)",
    "Adobe (Firefly)",
    # Pure Semiconductor Hardware
    "Samsung Semiconductor", "Broadcom",
    # Industrial Conglomerates
    "Siemens", "Rockwell Automation", "Honeywell", "Schneider Electric",
]

removed_count = 0
for company in remove_list:
    if company in existing:
        del existing[company]
        removed_count += 1

print(f"Removed: {removed_count}")
print(f"After removal: {len(existing)}")

# NEW COMPANIES TO ADD (compiled from all agents, deduplicated)
new_companies = OrderedDict([
    # === BATCH 1: Cloud, Enterprise SaaS, DevOps ===
    ("Amazon Web Services (AWS)", "https://www.amazon.jobs/en/teams/aws"),
    ("Microsoft Azure", "https://careers.microsoft.com/"),
    ("Google Cloud", "https://careers.google.com"),
    ("Oracle Cloud Infrastructure", "https://www.oracle.com/careers/"),
    ("VMware (Broadcom)", "https://careers.vmware.com/"),
    ("Nutanix", "https://www.nutanix.com/company/careers"),
    ("Rackspace Technology", "https://rackspace.jobs/"),
    ("Akamai Technologies", "https://www.akamai.com/careers"),
    ("Fastly", "https://www.fastly.com/about/careers"),
    ("F5 Networks", "https://www.f5.com/company/careers"),
    ("Infoblox", "https://www.infoblox.com/company/careers/"),
    ("NetApp", "https://careers.netapp.com/search-jobs"),
    ("Pure Storage", "https://www.purestorage.com/company/careers.html"),
    ("Dell Technologies", "https://jobs.dell.com/en"),
    ("Hewlett Packard Enterprise", "https://careers.hpe.com/us/en"),
    ("Tenable", "https://www.tenable.com/careers"),
    ("Qualys", "https://www.qualys.com/careers"),
    ("Imperva", "https://www.imperva.com/company/careers/"),
    ("Lacework", "https://www.lacework.com/careers"),
    ("Sysdig", "https://www.sysdig.com/careers"),
    ("Wiz", "https://www.wiz.io/careers"),
    ("Orca Security", "https://orca.security/about/careers/"),
    ("BeyondTrust", "https://www.beyondtrust.com/company/overview/careers"),
    ("Delinea", "https://delinea.com/careers"),
    ("Ping Identity", "https://www.pingidentity.com/en/company/careers.html"),
    ("Saviynt", "https://saviynt.com/careers"),
    ("Kyndryl", "https://www.kyndryl.com/us/en/careers"),
    ("Capgemini", "https://www.capgemini.com/us-en/careers/"),
    ("Wipro", "https://careers.wipro.com/"),
    ("Tata Consultancy Services", "https://www.tcs.com/careers"),
    ("Perficient", "https://www.perficient.com/careers"),
    ("Presidio", "https://www.presidio.com/careers/"),
    ("Lumen Technologies", "https://jobs.lumen.com/"),
    ("SAP", "https://jobs.sap.com/"),
    ("Adobe", "https://careers.adobe.com/"),
    ("Zoom", "https://careers.zoom.us/"),
    ("Box", "https://www.box.com/en-us/jobs"),
    ("Atlassian", "https://www.atlassian.com/company/careers"),
    ("MongoDB", "https://www.mongodb.com/careers"),
    ("Datadog", "https://careers.datadoghq.com/"),
    ("New Relic", "https://newrelic.com/careers"),
    ("PagerDuty", "https://careers.pagerduty.com/"),
    ("GitLab", "https://about.gitlab.com/jobs/"),
    ("Sumo Logic", "https://www.sumologic.com/company/careers"),
    ("Grafana Labs", "https://grafana.com/careers/"),
    ("ClickHouse", "https://clickhouse.com/company/careers"),
    ("ClickUp", "https://clickup.com/careers"),
    ("Linear", "https://linear.app/careers"),
    ("Medallia", "https://jobs.medallia.com/"),
    ("Qualtrics", "https://www.qualtrics.com/careers/us/en"),
    ("Veeva Systems", "https://careers.veeva.com/"),
    ("Procore", "https://careers.procore.com/"),
    ("Guidewire Software", "https://careers.guidewire.com/"),
    ("Intuit", "https://jobs.intuit.com/"),
    ("Splunk (Cisco)", "https://careers.cisco.com/global/en/splunk"),
    ("SolarWinds", "https://www.solarwinds.com/company/careers"),
    ("GoTo (LogMeIn)", "https://www.goto.com/company/careers"),
    ("RingCentral", "https://www.ringcentral.com/us/en/careers.html"),
    ("Genesys", "https://jobs.genesys.com/"),
    ("Ceridian (Dayforce)", "https://www.ceridian.com/us/careers"),
    ("Appian", "https://careers.appian.com/"),
    ("Teradata", "https://careers.teradata.com/"),
    ("Informatica", "https://www.informatica.com/about-us/careers.html"),
    ("TIBCO Software", "https://careers.tibco.com/"),
    ("Progress Software", "https://www.progress.com/company/careers"),
    ("OpenText", "https://careers.opentext.com/"),
    ("Ivanti", "https://www.ivanti.com/company/careers"),
    ("ManageEngine (Zoho)", "https://careers.manageengine.com/"),
    ("Fivetran", "https://www.fivetran.com/careers"),
    ("Airbyte", "https://airbyte.com/company/careers"),
    ("Red Hat (IBM)", "https://www.redhat.com/en/jobs"),
    ("JFrog", "https://join.jfrog.com/"),
    ("CircleCI", "https://circleci.com/careers/"),
    ("Harness", "https://www.harness.io/company/careers"),
    ("Astronomer", "https://www.astronomer.io/careers/"),
    ("Kong Inc", "https://konghq.com/company/careers"),
    ("CloudBees", "https://www.cloudbees.com/careers"),
    ("Sonatype", "https://www.sonatype.com/company/careers"),
    ("Veracode", "https://www.veracode.com/about/careers"),
    ("Aqua Security", "https://www.aquasec.com/about/careers/"),
    ("LaunchDarkly", "https://launchdarkly.com/careers/"),
    ("Optimizely", "https://www.optimizely.com/careers/"),
    ("Contentful", "https://www.contentful.com/careers/"),
    ("Netlify", "https://www.netlify.com/careers/"),
    ("Codefresh", "https://codefresh.io/careers/"),
    ("MicroStrategy", "https://www.microstrategy.com/en/careers"),
    ("Puppet", "https://www.puppet.com/company/careers"),
    # === BATCH 2: Cybersecurity, Data Analytics, Networking ===
    ("SailPoint", "https://www.sailpoint.com/company/careers"),
    ("Forcepoint", "https://forcepoint.wd1.myworkdayjobs.com/external-careers"),
    ("RSA Security", "https://www.rsa.com/rsa-careers/"),
    ("Coalfire", "https://coalfire.com/about/careers"),
    ("Imprivata", "https://www.imprivata.com/company/careers"),
    ("McAfee", "https://careers.mcafee.com/"),
    ("Trellix", "https://careers.trellix.com/"),
    ("Cybereason", "https://www.cybereason.com/company/careers"),
    ("Rubrik", "https://www.rubrik.com/company/careers"),
    ("Drata", "https://drata.com/about/careers"),
    ("Huntress", "https://www.huntress.com/company/careers"),
    ("ThreatLocker", "https://www.threatlocker.com/company/careers"),
    ("Nozomi Networks", "https://www.nozominetworks.com/company/careers"),
    ("Illumio", "https://www.illumio.com/company/careers"),
    ("Axonius", "https://www.axonius.com/company/careers"),
    ("Torq", "https://torq.io/careers/"),
    ("Secureworks", "https://jobs.dell.com/en/category/secureworks-jobs/375/24185/1"),
    ("Securonix", "https://www.securonix.com/company/careers/"),
    ("SecurityScorecard", "https://securityscorecard.com/company/careers/"),
    ("Anomali", "https://www.anomali.com/company/careers"),
    ("Swimlane", "https://swimlane.com/careers/"),
    ("Fortra", "https://www.fortra.com/about/careers"),
    ("Dragos", "https://www.dragos.com/careers"),
    ("HackerOne", "https://www.hackerone.com/careers"),
    ("Red Canary", "https://redcanary.com/careers/"),
    ("JumpCloud", "https://jumpcloud.com/careers"),
    ("Immuta", "https://www.immuta.com/careers/"),
    ("Starburst", "https://www.starburst.io/careers/"),
    ("dbt Labs", "https://www.getdbt.com/about-us/careers"),
    ("Amplitude", "https://amplitude.com/careers"),
    ("Mixpanel", "https://mixpanel.com/jobs/"),
    ("Sigma Computing", "https://www.sigmacomputing.com/company/careers"),
    ("Monte Carlo", "https://www.montecarlodata.com/careers-at-monte-carlo/"),
    ("Hightouch", "https://hightouch.com/careers"),
    ("Hex", "https://hex.tech/careers/"),
    ("Metabase", "https://www.metabase.com/jobs"),
    ("Matillion", "https://www.matillion.com/careers"),
    ("Collibra", "https://www.collibra.com/us/en/careers"),
    ("Boomi", "https://boomi.com/company/careers/"),
    ("Alation", "https://www.alation.com/careers/"),
    ("Atlan", "https://atlan.com/careers/"),
    ("Cribl", "https://cribl.io/careers/"),
    ("Redpanda Data", "https://redpanda.com/careers"),
    ("Arista Networks", "https://www.arista.com/en/careers"),
    ("Ciena", "https://www.ciena.com/careers"),
    ("Calix", "https://www.calix.com/careers.html"),
    ("CommScope", "https://jobs.commscope.com/"),
    ("VIAVI Solutions", "https://www.viavisolutions.com/en-us/corporate/careers"),
    ("Keysight Technologies", "https://jobs.keysight.com/"),
    ("Viasat", "https://careers.viasat.com/jobs"),
    ("Zayo Group", "https://www.zayo.com/careers/"),
    ("Extreme Networks", "https://www.extremenetworks.com/about-extreme-networks/careers"),
    ("Cambium Networks", "https://www.cambiumnetworks.com/about-us/careers/"),
    ("Amdocs", "https://www.amdocs.com/careers"),
    # === BATCH 3: FinTech, HealthTech, EdTech ===
    ("Adyen", "https://careers.adyen.com/"),
    ("Marqeta", "https://www.marqeta.com/company/careers"),
    ("Brex", "https://www.brex.com/careers"),
    ("Chime", "https://careers.chime.com/en/"),
    ("Affirm", "https://www.affirm.com/careers"),
    ("Robinhood", "https://careers.robinhood.com/"),
    ("Coinbase", "https://www.coinbase.com/careers"),
    ("SoFi", "https://www.sofi.com/careers/"),
    ("LendingClub", "https://www.lendingclub.com/company/careers"),
    ("Bill.com", "https://www.bill.com/careers"),
    ("Paylocity", "https://www.paylocity.com/company/careers/"),
    ("Remitly", "https://careers.remitly.com/"),
    ("Betterment", "https://www.betterment.com/careers"),
    ("Fiserv", "https://www.careers.fiserv.com/"),
    ("FIS Global", "https://careers.fisglobal.com/us/en"),
    ("Global Payments", "https://jobs.globalpayments.com/en/"),
    ("Jack Henry", "https://careers.jackhenry.com/"),
    ("SS&C Technologies", "https://www.ssctech.com/careers/join-ssc"),
    ("Tradeweb", "https://www.tradeweb.com/who-we-are/careers/"),
    ("Nuvei", "https://www.nuvei.com/careers"),
    ("Payoneer", "https://www.payoneer.com/careers/"),
    ("Checkout.com", "https://www.checkout.com/careers"),
    ("Ripple", "https://ripple.com/careers/"),
    ("Kraken", "https://www.kraken.com/careers"),
    ("Gemini", "https://www.gemini.com/careers"),
    ("Fireblocks", "https://www.fireblocks.com/careers"),
    ("Chainalysis", "https://www.chainalysis.com/careers/"),
    ("Paxos", "https://www.paxos.com/careers"),
    ("ConsenSys", "https://consensys.io/careers"),
    ("Blend", "https://blend.com/company/careers/"),
    ("Q2", "https://www.q2.com/careers"),
    ("Block (Square)", "https://careers.squareup.com/us/en"),
    ("nCino", "https://www.ncino.com/company/careers"),
    ("Backbase", "https://www.backbase.com/careers/"),
    ("Mambu", "https://www.mambu.com/company/careers"),
    ("Flywire", "https://www.flywire.com/company/careers"),
    ("AvidXchange", "https://www.avidxchange.com/about/careers/"),
    ("Tipalti", "https://tipalti.com/company/careers/"),
    ("Nium", "https://www.nium.com/company/careers"),
    ("Epic Systems", "https://careers.epic.com/jobs/"),
    ("athenahealth", "https://careers.athenahealth.com/us/en/"),
    ("Oracle Health", "https://www.oracle.com/careers/opportunities/health-careers/"),
    ("Teladoc Health", "https://www.teladochealth.com/careers"),
    ("Amwell", "https://business.amwell.com/about-us/careers/jobs"),
    ("Doximity", "https://workat.doximity.com/"),
    ("Flatiron Health", "https://flatiron.com/careers"),
    ("Inovalon", "https://www.inovalon.com/careers/"),
    ("Definitive Healthcare", "https://www.definitivehc.com/about/careers"),
    ("Health Catalyst", "https://www.healthcatalyst.com/who-we-are/careers"),
    ("Netsmart", "https://www.ntst.com/company/careers-and-culture"),
    ("Evolent Health", "https://www.evolent.com/careers"),
    ("Waystar", "https://careers.waystar.com/"),
    ("Phreesia", "https://www.phreesia.com/company/careers/"),
    ("Lyra Health", "https://careers.lyrahealth.com/"),
    ("Hinge Health", "https://www.hingehealth.com/careers/"),
    ("Spring Health", "https://www.springhealth.com/careers"),
    ("Included Health", "https://includedhealth.com/careers/"),
    ("Headway", "https://headway.co/careers"),
    ("Noom", "https://www.noom.com/careers/job-listings/"),
    ("Transcarent", "https://transcarent.com/careers"),
    ("Innovaccer", "https://innovaccer.com/company/careers/"),
    ("Komodo Health", "https://www.komodohealth.com/careers"),
    ("Clarify Health", "https://www.clarifyhealth.com/about/careers"),
    ("Redox", "https://www.redoxengine.com/company/careers/"),
    ("Instructure (Canvas)", "https://www.instructure.com/about/careers"),
    ("Chegg", "https://www.chegg.com/about/working-at-chegg/jobs"),
    ("Udemy", "https://about.udemy.com/careers/"),
    ("Pluralsight", "https://www.pluralsight.com/careers"),
    ("Skillsoft", "https://www.skillsoft.com/about/careers"),
    ("2U / edX", "https://2u.com/careers/"),
    ("PowerSchool", "https://www.powerschool.com/company/careers/"),
    ("Ellucian", "https://careers.ellucian.com/jobs"),
    ("Anthology (Blackboard)", "https://www.anthology.com/about-us/careers"),
    ("Blackbaud", "https://careers.blackbaud.com/us/en/"),
    ("Turnitin", "https://www.turnitin.com/about/careers/"),
    ("IXL Learning", "https://www.ixl.com/company/careers"),
    ("Newsela", "https://newsela.com/careers"),
    ("HackerRank", "https://www.hackerrank.com/careers/home"),
    ("Kahoot", "https://kahoot.com/open-positions/"),
    ("Codecademy", "https://www.codecademy.com/about/careers"),
    ("MasterClass", "https://careers.masterclass.com/"),
    ("Guild Education", "https://www.guildeducation.com/about-us/careers/"),
    ("Degreed", "https://degreed.com/experience/careers/"),
    ("Cornerstone OnDemand", "https://www.cornerstoneondemand.com/careers/"),
    ("Renaissance Learning", "https://www.renaissance.com/careers/"),
    ("D2L (Desire2Learn)", "https://www.d2l.com/careers/"),
    ("Pearson", "https://pearson.jobs/"),
    ("Amplify", "https://www.amplify.com/careers"),
    ("Discovery Education", "https://www.discoveryeducation.com/company/careers/"),
    # === BATCH 4: E-commerce, Gaming, PropTech, HR Tech ===
    ("Wayfair", "https://www.aboutwayfair.com/careers"),
    ("Chewy", "https://careers.chewy.com/us/en"),
    ("Etsy", "https://careers.etsy.com/"),
    ("StockX", "https://careers.stockx.com/"),
    ("GOAT Group", "https://www.goat.com/careers"),
    ("Poshmark", "https://poshmark.com/careers"),
    ("ThredUp", "https://careers.thredup.com/us/en"),
    ("Faire", "https://www.faire.com/careers"),
    ("Klarna", "https://www.klarna.com/careers/"),
    ("BigCommerce", "https://www.bigcommerce.com/company/careers/"),
    ("Attentive", "https://www.attentive.com/careers"),
    ("Gorgias", "https://www.gorgias.com/careers"),
    ("Mirakl", "https://www.mirakl.com/careers"),
    ("ShipBob", "https://www.shipbob.com/careers/jobs/"),
    ("Rokt", "https://www.rokt.com/company/careers"),
    ("Avalara", "https://careers.avalara.com/careers-home/"),
    ("Salsify", "https://www.salsify.com/company/careers"),
    ("Bazaarvoice", "https://www.bazaarvoice.com/about/careers/"),
    ("Signifyd", "https://www.signifyd.com/careers/"),
    ("Loop Returns", "https://loopreturns.com/careers/"),
    ("Omnisend", "https://www.omnisend.com/careers/"),
    ("Epic Games", "https://www.epicgames.com/site/en-US/careers"),
    ("Riot Games", "https://www.riotgames.com/en/work-with-us/jobs"),
    ("Electronic Arts (EA)", "https://www.ea.com/careers"),
    ("Activision Blizzard", "https://careers.activisionblizzard.com/"),
    ("Take-Two Interactive", "https://careers.take2games.com/"),
    ("Ubisoft", "https://www.ubisoft.com/en-us/company/careers"),
    ("Unity Technologies", "https://unity.com/careers"),
    ("Niantic", "https://nianticlabs.com/careers"),
    ("Valve Corporation", "https://www.valvesoftware.com/en/jobs"),
    ("Bungie", "https://www.bungie.net/careers"),
    ("CD Projekt Red", "https://www.cdprojektred.com/en/jobs"),
    ("DraftKings", "https://careers.draftkings.com/"),
    ("FanDuel", "https://www.fanduel.careers/"),
    ("Playtika", "https://www.playtika.com/careers/all/"),
    ("Scopely", "https://scopely.com/careers/"),
    ("Warner Bros. Games", "https://careers.warnerbros.com/"),
    ("Zillow", "https://www.zillow.com/careers/"),
    ("Redfin", "https://careers.redfin.com/us/en"),
    ("Opendoor", "https://www.opendoor.com/careers"),
    ("Compass", "https://www.compass.com/careers/"),
    ("CoStar Group", "https://www.costargroup.com/careers"),
    ("RealPage", "https://www.realpage.com/careers/"),
    ("Yardi Systems", "https://careers.yardi.com/"),
    ("Buildium", "https://www.buildium.com/careers/"),
    ("MRI Software", "https://www.mrisoftware.com/about/careers/"),
    ("VTS", "https://www.vts.com/careers"),
    ("Entrata", "https://www.entrata.com/careers"),
    ("HomeLight", "https://www.homelight.com/careers"),
    ("SmartRent", "https://www.smartrent.com/company/careers/"),
    ("Notarize", "https://www.notarize.com/careers"),
    ("Rippling", "https://www.rippling.com/careers"),
    ("Lattice", "https://lattice.com/careers"),
    ("Greenhouse", "https://www.greenhouse.com/careers"),
    ("BambooHR", "https://www.bamboohr.com/careers/"),
    ("Deel", "https://www.deel.com/careers/"),
    ("HiBob", "https://www.hibob.com/careers/"),
    ("Culture Amp", "https://www.cultureamp.com/company/careers"),
    ("Leapsome", "https://www.leapsome.com/careers"),
    ("Personio", "https://www.personio.com/about-personio/careers/"),
    ("Remote.com", "https://remote.com/careers"),
    ("Oyster HR", "https://www.oysterhr.com/careers"),
    ("ADP", "https://jobs.adp.com/en/"),
    ("UKG", "https://www.ukg.com/company/careers"),
    ("TriNet", "https://www.trinet.com/about-us/careers"),
    ("iCIMS", "https://careers.icims.com/"),
    ("SmartRecruiters", "https://www.smartrecruitersscareers.com/"),
    ("15Five", "https://www.15five.com/about/careers/"),
    ("Pave", "https://www.pave.com/careers"),
    ("Checkr", "https://www.checkr.com/company/careers"),
    ("Paycor", "https://www.paycor.com/careers/"),
    # === BATCH 5: IT Services, Database, IAM, API Platforms ===
    ("HCL Technologies", "https://www.hcltech.com/careers"),
    ("Tech Mahindra", "https://careers.techmahindra.com/"),
    ("DXC Technology", "https://careers.dxc.com/"),
    ("NTT Data", "https://us.nttdata.com/en/careers"),
    ("Virtusa", "https://www.virtusa.com/careers"),
    ("Unisys", "https://www.unisys.com/about-us/careers"),
    ("Fujitsu", "https://www.fujitsu.com/us/about/resources/careers/"),
    ("LTIMindtree", "https://www.ltimindtree.com/careers/"),
    ("Mphasis", "https://careers.mphasis.com/"),
    ("CGI Group", "https://www.cgi.com/en/careers"),
    ("Guidehouse", "https://guidehouse.com/careers"),
    ("Conduent", "https://careers.conduent.com/us/en/"),
    ("WWT (World Wide Technology)", "https://www.wwt.com/corporate/who-we-are/careers"),
    ("Trace3", "https://www.trace3.com/careers"),
    ("Softchoice", "https://www.softchoice.com/about/careers"),
    ("Ness Digital Engineering", "https://www.ness.com/careers/"),
    ("CockroachDB", "https://www.cockroachlabs.com/careers/"),
    ("SingleStore", "https://www.singlestore.com/careers/"),
    ("Couchbase", "https://www.couchbase.com/careers/"),
    ("Redis", "https://redis.io/careers/"),
    ("Veeam", "https://careers.veeam.com/"),
    ("Cohesity", "https://www.cohesity.com/careers/"),
    ("Commvault", "https://www.commvault.com/careers"),
    ("Veritas", "https://www.veritas.com/en/ca/company/careers"),
    ("Cloudera", "https://www.cloudera.com/careers.html"),
    ("DataStax", "https://www.datastax.com/company/careers"),
    ("InfluxData", "https://www.influxdata.com/careers/"),
    ("Dremio", "https://www.dremio.com/careers/"),
    ("Omada Identity", "https://omadaidentity.com/company/careers/"),
    ("Transmit Security", "https://www.transmitsecurity.com/careers"),
    ("Silverfort", "https://www.silverfort.com/company/careers/"),
    ("ForgeRock", "https://www.forgerock.com/about-us/careers"),
    ("Zluri", "https://www.zluri.com/careers"),
    ("Workato", "https://www.workato.com/careers"),
    ("Jitterbit", "https://www.jitterbit.com/careers/"),
    ("Axway", "https://www.axway.com/en/company/careers"),
    ("SnapLogic", "https://www.snaplogic.com/company/careers"),
    ("Celigo", "https://www.celigo.com/careers/"),
    ("Tray.ai", "https://tray.io/careers"),
    ("Digibee", "https://www.digibee.com/careers/"),
    ("Zapier", "https://zapier.com/jobs"),
    ("WSO2", "https://wso2.com/careers/"),
    ("Cyclr", "https://cyclr.com/careers"),
    ("OutSystems", "https://www.outsystems.com/careers/"),
    ("Mendix", "https://www.mendix.com/careers/"),
    # === BATCH 6: AI/ML, Autonomous Vehicles, IoT, GreenTech ===
    ("Baseten", "https://www.baseten.co/careers/"),
    ("Modal Labs", "https://modal.com/careers"),
    ("Imbue", "https://imbue.com/careers/"),
    ("Typeface", "https://www.typeface.ai/careers"),
    ("LangChain", "https://www.langchain.com/careers"),
    ("Wayve", "https://wayve.ai/careers/"),
    ("Aurora Innovation", "https://aurora.tech/careers"),
    ("Zoox", "https://zoox.com/careers"),
    ("Mobileye", "https://careers.mobileye.com/"),
    ("Luminar Technologies", "https://www.luminartech.com/careers"),
    ("Innoviz Technologies", "https://innoviz.tech/careers"),
    ("Applied Intuition", "https://www.appliedintuition.com/careers"),
    ("Waabi", "https://waabi.ai/careers/"),
    ("Kodiak Robotics", "https://www.kodiak.ai/careers"),
    ("Torc Robotics", "https://torc.ai/careers"),
    ("Stack AV", "https://www.stackav.com/careers"),
    ("Foretellix", "https://www.foretellix.com/careers/"),
    ("Ridecell", "https://ridecell.com/careers/"),
    ("Impinj", "https://www.impinj.com/about-us/careers"),
    ("Digi International", "https://www.digi.com/company/careers"),
    ("Particle Industries", "https://www.particle.io/careers/"),
    ("ZEDEDA", "https://zededa.com/company/careers/"),
    ("ClearBlade", "https://www.clearblade.com/careers/"),
    ("Memfault", "https://memfault.com/careers/"),
    ("Edge Impulse", "https://edgeimpulse.com/careers"),
    ("PTC", "https://www.ptc.com/en/careers"),
    ("Cradlepoint", "https://cradlepoint.com/about/careers/"),
    ("Sunrun", "https://careers.sunrun.com/"),
    ("Aurora Solar", "https://aurorasolar.com/careers/"),
    ("Omnidian", "https://www.omnidian.com/careers/"),
    ("Redwood Materials", "https://www.redwoodmaterials.com/join/"),
    ("QuantumScape", "https://careers.quantumscape.com/"),
    ("Commonwealth Fusion Systems", "https://cfs.energy/careers"),
    ("Form Energy", "https://formenergy.com/careers/"),
    ("Solid Power", "https://www.solidpowerbattery.com/careers/"),
    ("Crusoe Energy", "https://crusoe.ai/careers/"),
    ("Oklo", "https://oklo.com/careers"),
    ("Span.IO", "https://www.span.io/careers"),
    ("WeaveGrid", "https://www.weavegrid.com/careers"),
    ("Fluence Energy", "https://fluenceenergy.com/careers/"),
    ("Amp Robotics", "https://amprobotics.com/careers"),
    # === BATCH 7: Big Tech, AdTech, LegalTech, Supply Chain, GovTech ===
    ("Google (Alphabet)", "https://careers.google.com"),
    ("Meta", "https://www.metacareers.com/"),
    ("Apple", "https://www.apple.com/careers/us/"),
    ("Microsoft", "https://careers.microsoft.com/"),
    ("Amazon", "https://www.amazon.jobs/en/"),
    ("LinkedIn", "https://careers.linkedin.com/"),
    ("Nuance (Microsoft)", "https://www.nuance.com/about-us/careers.html"),
    ("Spotify", "https://www.lifeatspotify.com/jobs"),
    ("The Trade Desk", "https://careers.thetradedesk.com/"),
    ("DoubleVerify", "https://doubleverify.com/company/careers"),
    ("IAS (Integral Ad Science)", "https://integralads.com/about-ias/careers/"),
    ("Magnite", "https://www.magnite.com/careers/"),
    ("PubMatic", "https://pubmatic.com/careers/home/"),
    ("OpenX", "https://www.openx.com/careers/"),
    ("Index Exchange", "https://www.indexexchange.com/careers/"),
    ("Taboola", "https://www.taboola.com/careers"),
    ("Outbrain", "https://www.outbrain.com/careers"),
    ("Quantcast", "https://www.quantcast.com/careers/"),
    ("StackAdapt", "https://www.stackadapt.com/careers"),
    ("Zeta Global", "https://zetaglobal.com/company/careers/"),
    ("Thomson Reuters", "https://careers.thomsonreuters.com/"),
    ("Wolters Kluwer", "https://careers.wolterskluwer.com/en"),
    ("Relativity", "https://www.relativity.com/company/careers/"),
    ("iManage", "https://imanage.com/about/the-company/careers/"),
    ("Mitratech", "https://mitratech.com/about-us/careers/"),
    ("CS DISCO", "https://www.csdisco.com/careers"),
    ("Filevine", "https://www.filevine.com/jobs/"),
    ("Litera", "https://www.litera.com/careers"),
    ("EvenUp", "https://www.evenuplaw.com/careers/"),
    ("Exterro", "https://www.exterro.com/careers"),
    ("o9 Solutions", "https://o9solutions.com/careers"),
    ("RELEX Solutions", "https://www.relexsolutions.com/careers/"),
    ("E2open", "https://www.e2open.com/careers/"),
    ("Coupa", "https://careers.coupa.com/"),
    ("Infor", "https://www.infor.com/about/careers"),
    ("Stord", "https://www.stord.com/careers"),
    ("HERE Technologies", "https://www.here.com/careers"),
    ("Esri", "https://www.esri.com/en-us/about/careers/overview"),
    ("Trimble", "https://careers.trimble.com/"),
    ("GDIT", "https://www.gdit.com/careers/"),
    ("CACI", "https://careers.caci.com/"),
    ("ManTech", "https://careers.mantech.com/"),
    ("Peraton", "https://www.careers.peraton.com/search-jobs"),
    ("Maximus Federal", "https://www.maximus.com/careers"),
    ("ICF International", "https://careers.icf.com/us/en"),
    ("Noblis", "https://careers.noblis.org/jobs"),
    ("Amentum", "https://www.amentumcareers.com/"),
    ("Accenture Federal Services", "https://www.accenture.com/us-en/careers/local/federal-careers"),
    ("CGI Federal", "https://www.cgi.com/en/careers"),
    ("Parsons", "https://www.parsons.com/careers/"),
    ("NBCUniversal", "https://www.nbcunicareers.com/careers"),
    ("Comcast", "https://jobs.comcast.com/"),
    ("Warner Bros. Discovery", "https://careers.wbd.com/"),
    ("Disney Tech", "https://jobs.disneycareers.com/technology"),
])

# Add new companies (skip duplicates already in existing)
added = 0
skipped_dupes = []
for company, url in new_companies.items():
    # Check if already exists (exact or close match)
    if company not in existing:
        existing[company] = url
        added += 1
    else:
        skipped_dupes.append(company)

print(f"New companies added: {added}")
print(f"Skipped (already existed): {len(skipped_dupes)}")
print(f"Final total: {len(existing)}")

# Write to new Excel file
wb_new = openpyxl.Workbook()
ws_new = wb_new.active
ws_new.title = "Sheet"
ws_new.append(["Company", "Career URL"])

for company, url in existing.items():
    ws_new.append([company, url])

# Auto-adjust column widths
ws_new.column_dimensions['A'].width = 40
ws_new.column_dimensions['B'].width = 70

wb_new.save('ai_ml_companies_list.xlsx')
print("\nSaved to ai_ml_companies_list.xlsx")
